language: python

python:
  - "3.6"

env:
  - TENSORFLOW_VERSION=1.5
  - TENSORFLOW_VERSION=1.6
  - TENSORFLOW_VERSION=1.7

before_install:

# command to install dependencies
install:
  - pip install -q .
  - pip install numpy --upgrade # prevents TF1.5 and Python 3.6 from failing due to numpy error
  - pip install -q tensorflow==$TENSORFLOW_VERSION
 

# command to run tests
script:
  - python tests/unittests_estimators.py
  - python tests/unittests_evaluations.py
  - python tests/unittests_simulations.py
  - python tests/unittests_utils.py

notifications:
  email:
    recipients:
      - jonas.rothfuss@gmail.com
      - fabioferreira@mailbox.org
    on_success: never
    on_failure: never
